name: business
description: Kapitalist business logic

environment:
  sdk: ">= 2.0.0 <3.0.0"

dependencies:
  # HTTP
  http: ^0.12.0

  # Shared Preferences
  shared_preferences: ^0.5.0

  # Redux
  async_redux: ^2.9.0

  # Built Value + Collection
  built_value: ^7.1.0
  built_collection: ^4.3.0

dev_dependencies:
  build_runner: ^1.5.0
  built_value_generator: ^7.1.0

  test: ^1.14.0

  flutter_test:
    sdk: flutter